config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'pages#inicio'

  get 'pages/inicio', to: 'pages#inicio', as: 'inicio'
  get 'pages/aliados', to: 'pages#aliados', as: 'aliados'
  get 'pages/clientes', to: 'pages#clientes', as: 'clientes'
  get 'pages/consumidor', to: 'pages#consumidor', as: 'consumidor'
  get 'pages/contacto', to: 'pages#contacto', as: 'contacto'
  get 'pages/productos', to: 'pages#productos', as: 'productos'
  get 'pages/servicios', to: 'pages#servicios', as: 'servicios'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/content.rb
class Content < ActiveRecord::Base
	attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def inicio
    @contents = Content.all 
  end

  def servicios
  end

  def productos
  end

  def aliados
  end

  def clientes
  end

  def contacto
  end

  def consumidor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/elements/_content.html.erb
<% @contents.each do |content| %>
  <div class="large-3 medium-3 small-6 columns text-center end">
    <%= image_tag attachment_url(content, :image, :fill, 200, 150), style: "display: block; margin-left: auto; margin-right: auto;" %>
    <br>
    <h4 style="color:#23557F"><strong><%= content.title%>:</strong></h4>

    <p class="text-justify" style="color:#23557F"><%= content.info %></p>

    <a href="" class="button" style="width: 77%">Conoce más</a>
  </div>
<% end %>

app/views/elements/_navbar.html.erb
<div class="fixed contain-to-grid" style="-webkit-box-shadow: 10px 5px 25px 7px rgba(204,204,204,0.43);
-moz-box-shadow: 10px 5px 25px 7px rgba(204,204,204,0.43);
box-shadow: 10px 5px 25px 7px rgba(204,204,204,0.43);">
  <nav class="top-bar" data-topbar>        
    <ul class="title-area">
      <li class="name">
        <h1><a href="/"><img src="/assets/logo.png"</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
        
        <!--first row-->
        
    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="right" style="background-color: #7193AA !important">
        <li class="active"><a ><i class="fa fa-home fa-2x"></i></a></li>
        <li class="active"><a ><i class="fa fa-users fa-2x"></i></a></li>
        <li class="active"><a ><i class="fa fa-credit-card fa-2x"></i></a></li>
        <li class="active"><a ><i class="fa fa-phone fa-2x"></i></a></li>
        <li class="active"><a ><i class="fa fa-share fa-2x"></i></a></li>                    
      </ul>     
     
    </section>

        
    <section class="top-bar-section">
      
      <ul class="right">
        <li><%= link_to "Quiénes Somos", productos_path %></li>
        <li class="divider"></li>      
        <li><%= link_to "Productos", servicios_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Servicios", aliados_path %></li>
        <li class="divider"></li>      
        <li><%= link_to "Clientes", clientes_path %></li>              
      </ul>     
    </section>
        
        
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "GRQ" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: "elements/navbar" %>
    <%= yield %>
   <div id="footer" style="background:#F9B233 !important; -webkit-box-shadow: 0px -3px 5px 0px rgba(230,230,230,1);
-moz-box-shadow: 0px -3px 5px 0px rgba(230,230,230,1);
box-shadow: 0px -3px 5px 0px rgba(230,230,230,1);">
        
        <div class="row end">
          <br>
            <div class="large-3 medium-3 small-6 columns">
              <h4>Logo</h4>
              <ul id="cerca"><a href="/pages/servicios" id="cerca2">Nuestros Servicios</a></ul>
              <ul id="cerca"><a href="/pages/productos" id="cerca2">Nuestros Productos</a></ul>
              <ul id="cerca"><a href="/pages/aliados" id="cerca2">Compañias Aliadas</a></ul>
              <ul id="cerca"><a href="/pages/clientes" id="cerca2">Nuestros Clientes</a></ul>
              <ul id="cerca"><a href="/pages/consumidor" id="cerca2">Consumidor Financiero</a></ul>
              <ul id="cerca"><a href="/pages/contacto" id="cerca2">Contacto</a></ul>
            </div>
            <div class="large-3 medium-3 small-6 columns">
              <h4><strong>Enlaces Rápidos</strong></h4>
              <ul id="cerca"><a href="/pages/servicios" id="cerca2">Nuestros Servicios</a></ul>
              <ul id="cerca"><a href="/pages/productos" id="cerca2">Nuestros Productos</a></ul>
              <ul id="cerca"><a href="/pages/aliados" id="cerca2">Compañias Aliadas</a></ul>
              <ul id="cerca"><a href="/pages/clientes" id="cerca2">Nuestros Clientes</a></ul>
              <ul id="cerca"><a href="/pages/consumidor" id="cerca2">Consumidor Financiero</a></ul>
              <ul id="cerca"><a href="/pages/contacto" id="cerca2">Contacto</a></ul>
            </div>
             <div class="large-3 medium-3 small-6 columns">
              <h4 class="text-center"><strong>Contáctenos:</strong></h4>
              <p class="text-center">Tel:+57(6)887 5100<br>
              Cra 23A # 74 - 71 <br>
              <strong>Oficina 802</strong><br>
              Manizales, Colombia</p>
            </div>
             <div class="large-3 medium-3 small-6 columns">
              <h4 class="text-center"><strong>Redes Sociales</strong></h4>
              <p class="text-center">Tel:+57(6)887 5100<br>
              Cra 23A # 74 - 71 <br>
              <strong>Oficina 802</strong><br>
              Manizales, Colombia</p>
            </div>
          <br>
        </div>
        <br>
        
      </div> 

    <script>
      $(document).foundation();
       $(document).ready(function() {
         fixFooter();//at page load
       });

       $(window).resize(function() {
         fixFooter();//at page resize
       });

       function fixFooter() {
         footer=$("#footer");
         height=footer.height();
         paddingTop=parseInt(footer.css('padding-top'),10);//zero if is undefined
         paddingBottom=parseInt(footer.css('padding-bottom'),10);//zero if is undefined
         totalHeight=(height+paddingTop+paddingBottom);
         footerPosition=footer.position();
         windowHeight=$(window).height();
         height=(windowHeight - footerPosition.top)-totalHeight;
         if ( height > 0 ) {
           footer.css({
             'margin-top': (height) + 'px'
           });
         }
       }
    </script>
  </body>
</html>

app/views/pages/aliados.html.erb
<h1>Pages#aliados</h1>
<p>Find me in app/views/pages/aliados.html.erb</p>

app/views/pages/clientes.html.erb
<h1>Pages#clientes</h1>
<p>Find me in app/views/pages/clientes.html.erb</p>

app/views/pages/consumidor.html.erb
<h1>Pages#consumidor</h1>
<p>Find me in app/views/pages/consumidor.html.erb</p>

app/views/pages/contacto.html.erb
<h1>Pages#contacto</h1>
<p>Find me in app/views/pages/contacto.html.erb</p>

app/views/pages/inicio.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="example-orbit" data-orbit data-options="pause_on_hover:false; timer_speed:7000;">
      <li><img src="http://placehold.it/970x500" alt="slide 1">
          <div class="orbit-caption">
            <h2 style="color:white !important" class="text-right">Conoce Nuestra Empresa</h2>
            <h3 style="color:#1F4056 !important" class="text-right">y lo que podemos ofrecerte</h3>
          </div>
      </li>
      <li><img src="http://placehold.it/970x500" alt="slide 2">
          <div class="orbit-caption">
            <h2 style="color:white !important" class="text-right">La Educación y La Familia</h2>
            <h3 style="color:#1F4056 !important" class="text-right">son nuestra priodidad</h3>
          </div>
      </li>
      <li><img src="http://placehold.it/970x500" alt="slide 3">
          <div class="orbit-caption">
            <h2 style="color:white !important" class="text-right">¿Estas Protegido?</h2>
            <h3 style="color:#1F4056 !important" class="text-right">Consulta con Nosotros</h3>
          </div>
      </li>
      <li><img src="http://placehold.it/970x500" alt="slide 4">
          <div class="orbit-caption">
            <h2 style="color:white !important" class="text-right">¿Estas Intranquilo?</h2>
            <h3 style="color:#1F4056 !important" class="text-right">Podemos ayudarte</h3>
          </div>
      </li>
      <li><img src="http://placehold.it/970x500" alt="slide 4">
          <div class="orbit-caption">
            <h2 style="color:white !important" class="text-right">¿Preocupado por el futuro?</h2>
            <h3 style="color:#1F4056 !important" class="text-right">nosotros te proteguemos en todo momento</h3>
          </div>
      </li>
    </ul>
  </div>

  <div class="large-12 columns">
    <h1 class="text-center" style="font-size: 50px; color: #183A51 !important; font-weight: bold;">Encuentra tu seguro indicado</h1>
    <br>
    <br>
  </div>

  <div class="large-12 columns end">
    <%= render partial: 'elements/content' %>
  </div>

  <hr>
    <img src="/assets/banner.png" style="height: 250px; width: 900px; display: block; margin-left: auto; margin-right: auto;">
    <br>
    <br>
    <br>
</div>

app/views/pages/productos.html.erb
<h1>Pages#productos</h1>
<p>Find me in app/views/pages/productos.html.erb</p>

app/views/pages/servicios.html.erb
<h1>Pages#servicios</h1>
<p>Find me in app/views/pages/servicios.html.erb</p>